-- Insertion des données dans Products de type Accessoires --
INSERT INTO Products VALUES (NULL, 'Montre Tommy Hilfiger', 'img/Accessoires/montre-1.jpg', 'Montre Tommy Hilfiger', 298.00);
INSERT INTO Products VALUES (NULL, 'Montre Jack Mason', 'img/Accessoires/montre-3.jpg', 'Montre Jack Mason', 398.00);
INSERT INTO Products VALUES (NULL, 'Montre à gousset', 'img/Accessoires/montre-4.jpg', 'Montre à gousset', 168.00);
INSERT INTO Products VALUES (NULL, 'Montre Festina', 'img/Accessoires/montre-6.jpg', 'Montre Festina', 180.00);
INSERT INTO Products VALUES (NULL, 'Montre Fossil', 'img/Accessoires/montre-7.jpg', 'Montre Fossil', 235.00);
INSERT INTO Products VALUES (NULL, 'Montre Candino', 'img/Accessoires/montre-8.jpg', 'Montre Candino', 114.00);
INSERT INTO Products VALUES (NULL, 'Montre Fossil', 'img/Accessoires/montre-15.jpg', 'Montre Fossil', 340.00);
INSERT INTO Products VALUES (NULL, 'Apple Watch', 'img/Accessoires/montre-14.jpg', 'Apple Watch', 269.00);
INSERT INTO Products VALUES (NULL, 'Montre en bois', 'img/Accessoires/montre-17.jpg', 'Montre en bois', 120.00);
INSERT INTO Products VALUES (NULL, 'Montre Frédérique Constant', 'img/Accessoires/montre-11.jpg', 'Montre Frédérique Constant', 650.00);
INSERT INTO Products VALUES (NULL, 'Collier Lorer', 'img/Accessoires/collier-1.jpg', 'Collier Lorer', 67.00);
INSERT INTO Products VALUES (NULL, 'Bracelet', 'img/Accessoires/bracelet-1.jpg', 'Bracelet', 45.00);
INSERT INTO Products VALUES (NULL, 'Bracelet', 'img/Accessoires/bracelet-2.jpg', 'Bracelet', 38.00);
INSERT INTO Products VALUES (NULL, 'Casquette', 'img/Accessoires/casquette-1.jpg', 'Casquette', 40.00);
INSERT INTO Products VALUES (NULL, 'Chapeau', 'img/Accessoires/chapeau-1.jpg', 'Chapeau', 55.00);
INSERT INTO Products VALUES (NULL, 'Casquette', 'img/Accessoires/casquette-3.jpg', 'Casquette', 42.00);
INSERT INTO Products VALUES (NULL, 'Lunettes', 'img/Accessoires/lunettes-1.jpg', 'Lunettes', 40.00);

-- Insertion des données dans Products de type Vêtements  --
INSERT INTO Products VALUES (NULL, 'Veste militaire', 'img/Vetements/vetement-1.jpg', 'Veste militaire', 70.00);
INSERT INTO Products VALUES (NULL, 'Veste Tommy Hilfiger', 'img/Vetements/vetement-2.jpg', 'Veste Tommy Hilfiger', 120.00);
INSERT INTO Products VALUES (NULL, 'Pull basic', 'img/Vetements/vetement-3.jpg', 'Pull basic', 65.00);
INSERT INTO Products VALUES (NULL, 'Veste en jean', 'img/Vetements/vetement-4.jpg', 'Veste en jean', 92.00);
INSERT INTO Products VALUES (NULL, 'Veste en cuir', 'img/Vetements/vetement-5.jpg', 'Veste en cuir', 324.00);
INSERT INTO Products VALUES (NULL, 'Hoddie oversize', 'img/Vetements/vetement-6.jpg', 'Hoddie oversize', 62.00);
INSERT INTO Products VALUES (NULL, 'Col roulé blanc', 'img/Vetements/vetement-8.jpg', 'Col roulé blanc', 49.00);
INSERT INTO Products VALUES (NULL, 'Costume 2 pièces', 'img/Vetements/vetement-9.jpg', 'Costume 2 pièces', 178.00);
INSERT INTO Products VALUES (NULL, 'Tee-shirt basic', 'img/Vetements/vetement-10.jpg', 'Tee-shirt basic', 30.00);
INSERT INTO Products VALUES (NULL, 'Pull col rond', 'img/Vetements/vetement-11.jpg', 'Pull col rond', 49.00);
INSERT INTO Products VALUES (NULL, 'Tee-shirt basic', 'img/Vetements/vetement-12.jpg', 'Tee-shirt basic', 44.00);
INSERT INTO Products VALUES (NULL, 'Tee-shirt basic', 'img/Vetements/vetement-13.jpg', 'Tee-shirt basic', 38.00);
INSERT INTO Products VALUES (NULL, 'Veste en jean', 'img/Vetements/vetement-14.jpg', 'Veste en jean', 99.00);
INSERT INTO Products VALUES (NULL, 'Manteau beige', 'img/Vetements/vetement-15.jpg', 'Manteau beige', 120.00);
INSERT INTO Products VALUES (NULL, 'Hoodie', 'img/Vetements/vetement-16.jpg', 'Hoodie', 39.00);

-- Insertion des données dans Products de type Customs --
INSERT INTO Products VALUES (NULL, 'AF1 Smile', 'img/Customs/Custom-1.jpg', 'AF1 Smile', 150.00);
INSERT INTO Products VALUES (NULL, 'AF1 Cartoon', 'img/Customs/Custom-2.jpg', 'AF1 Cartoon', 160.00);
INSERT INTO Products VALUES (NULL, 'AF1 Cartoon', 'img/Customs/Custom-3.jpg', 'AF1 Cartoon', 160.00);
INSERT INTO Products VALUES (NULL, 'Jordan 1 Demon Slayer', 'img/Customs/Custom-5.webp', 'Jordan 1 Demon Slayer', 142.00);
INSERT INTO Products VALUES (NULL, 'AF1 Dragon Ball Z', 'img/Customs/Custom-6.jpg', 'AF1 Dragon Ball Z', 150.00);
INSERT INTO Products VALUES (NULL, 'Jordan 1 Zoro', 'img/Customs/Custom-8.jpg', 'Jordan 1 Zoro', 167.00);

-- Insertion des données dans Products de type Chaussures --
INSERT INTO Products VALUES (NULL, 'Converse', 'img/Chaussures/chaussures-1.jpg', 'Converse', 120.00);
INSERT INTO Products VALUES (NULL, 'Bottines', 'img/Chaussures/chaussures-2.jpg', 'Bottines', 79.00);
INSERT INTO Products VALUES (NULL, 'Bottines basses Malfroid', 'img/Chaussures/chaussures-3.jpg', 'Bottines basses Malfroid', 160.00);
INSERT INTO Products VALUES (NULL, 'Converses x Off-White', 'img/Chaussures/chaussures-4.jpg', 'Converses x Off-White', 1600.00);
INSERT INTO Products VALUES (NULL, 'Nike dunk high', 'img/Chaussures/chaussures-5.jpeg', 'Nike dunk high', 100.00);
INSERT INTO Products VALUES (NULL, 'Converses x Comme des garçons', 'img/Chaussures/chaussures-6.webp', 'Converses x Comme des garçons', 119.00);
INSERT INTO Products VALUES (NULL, 'Bottines', 'img/Chaussures/chaussures-7.webp', 'Bottines', 83.00);
INSERT INTO Products VALUES (NULL, 'Basket Martin Valen', 'img/Chaussures/chaussures-8.jpg', 'Basket Martin Valen', 99.00);
INSERT INTO Products VALUES (NULL, 'Nike Blazer Low Sacai KAWS Red', 'img/Chaussures/chaussures-9.jpeg', 'Nike Blazer Low Sacai KAWS Red', 138.00);
INSERT INTO Products VALUES (NULL, 'Nike Air Jordan 1', 'img/Chaussures/chaussures-10.jpg', 'Nike Air Jordan 1', 129.00);
INSERT INTO Products VALUES (NULL, 'Nike AD1 x Carhart', 'img/Chaussures/chaussures-11.jpg', 'Nike AF1 x Carhart', 89.00);
INSERT INTO Products VALUES (NULL, 'Adidas Yeezy 500 Desert Rat Blush', 'img/Chaussures/chaussures-13.jpg', 'Adidas Yeezy 500 Desert Rat Blush', 330.00);
INSERT INTO Products VALUES (NULL, 'K-SWISS', 'img/Chaussures/chaussures-14.jpg', 'K-SWISS', 85.00);
INSERT INTO Products VALUES (NULL, 'Basket', 'img/Chaussures/chaussures-15.jpg', 'Basket', 79.00);

-- Insertion des données dans Accessories --
INSERT INTO Accessories VALUES (1);
INSERT INTO Accessories VALUES (2);
INSERT INTO Accessories VALUES (3);
INSERT INTO Accessories VALUES (4);
INSERT INTO Accessories VALUES (5);
INSERT INTO Accessories VALUES (6);
INSERT INTO Accessories VALUES (7);
INSERT INTO Accessories VALUES (8);
INSERT INTO Accessories VALUES (9);
INSERT INTO Accessories VALUES (10);
INSERT INTO Accessories VALUES (11);
INSERT INTO Accessories VALUES (12);
INSERT INTO Accessories VALUES (13);
INSERT INTO Accessories VALUES (14);
INSERT INTO Accessories VALUES (15);
INSERT INTO Accessories VALUES (16);
INSERT INTO Accessories VALUES (17);

-- Insertion des données dans Clothes --
INSERT INTO Clothes VALUES (18);
INSERT INTO Clothes VALUES (19);
INSERT INTO Clothes VALUES (20);
INSERT INTO Clothes VALUES (21);
INSERT INTO Clothes VALUES (22);
INSERT INTO Clothes VALUES (23);
INSERT INTO Clothes VALUES (24);
INSERT INTO Clothes VALUES (25);
INSERT INTO Clothes VALUES (26);
INSERT INTO Clothes VALUES (27);
INSERT INTO Clothes VALUES (28);
INSERT INTO Clothes VALUES (29);
INSERT INTO Clothes VALUES (30);
INSERT INTO Clothes VALUES (31);
INSERT INTO Clothes VALUES (32);

-- Insertion des données dans Customs --
INSERT INTO Customs VALUES (33);
INSERT INTO Customs VALUES (34);
INSERT INTO Customs VALUES (35);
INSERT INTO Customs VALUES (36);
INSERT INTO Customs VALUES (37);
INSERT INTO Customs VALUES (38);

-- Insertion des données dans Shoes --
INSERT INTO Shoes VALUES (39);
INSERT INTO Shoes VALUES (40);
INSERT INTO Shoes VALUES (41);
INSERT INTO Shoes VALUES (42);
INSERT INTO Shoes VALUES (43);
INSERT INTO Shoes VALUES (44);
INSERT INTO Shoes VALUES (45);
INSERT INTO Shoes VALUES (46);
INSERT INTO Shoes VALUES (47);
INSERT INTO Shoes VALUES (48);
INSERT INTO Shoes VALUES (49);
INSERT INTO Shoes VALUES (50);
INSERT INTO Shoes VALUES (51);
INSERT INTO Shoes VALUES (52);

-- Insertion des données dans Stock --
INSERT INTO Stock VALUES ('Acc', 1, 3);
INSERT INTO Stock VALUES ('Acc', 2, 1);
INSERT INTO Stock VALUES ('Acc', 3, 2);
INSERT INTO Stock VALUES ('Acc', 4, 1);
INSERT INTO Stock VALUES ('Acc', 5, 0);
INSERT INTO Stock VALUES ('Acc', 6, 0);
INSERT INTO Stock VALUES ('Acc', 7, 4);
INSERT INTO Stock VALUES ('Acc', 8, 3);
INSERT INTO Stock VALUES ('Acc', 9, 2);
INSERT INTO Stock VALUES ('Acc', 10, 1);
INSERT INTO Stock VALUES ('Acc', 11, 2);
INSERT INTO Stock VALUES ('Acc', 12, 0);
INSERT INTO Stock VALUES ('Acc', 13, 1);
INSERT INTO Stock VALUES ('Acc', 14, 1);
INSERT INTO Stock VALUES ('Acc', 15, 3);
INSERT INTO Stock VALUES ('Acc', 16, 0);
INSERT INTO Stock VALUES ('Acc', 17, 4);

INSERT INTO Stock VALUES ('XS', 18, 7);
INSERT INTO Stock VALUES ('S', 18, 0);
INSERT INTO Stock VALUES ('M', 18, 2);
INSERT INTO Stock VALUES ('L', 18, 3);
INSERT INTO Stock VALUES ('XL', 18, 0);
INSERT INTO Stock VALUES ('XS', 19, 1);
INSERT INTO Stock VALUES ('S', 19, 0);
INSERT INTO Stock VALUES ('M', 19, 1);
INSERT INTO Stock VALUES ('L', 19, 2);
INSERT INTO Stock VALUES ('XL', 19, 0);
INSERT INTO Stock VALUES ('XS', 20, 1);
INSERT INTO Stock VALUES ('S', 20, 0);
INSERT INTO Stock VALUES ('M', 20, 3);
INSERT INTO Stock VALUES ('L', 20, 2);
INSERT INTO Stock VALUES ('XL', 20, 0);
INSERT INTO Stock VALUES ('XS', 21, 1);
INSERT INTO Stock VALUES ('S', 21, 1);
INSERT INTO Stock VALUES ('M', 21, 0);
INSERT INTO Stock VALUES ('L', 21, 2);
INSERT INTO Stock VALUES ('XL', 21, 2);
INSERT INTO Stock VALUES ('XS', 22, 4);
INSERT INTO Stock VALUES ('S', 22, 1);
INSERT INTO Stock VALUES ('M', 22, 3);
INSERT INTO Stock VALUES ('L', 22, 0);
INSERT INTO Stock VALUES ('XL', 22, 0);
INSERT INTO Stock VALUES ('XS', 23, 1);
INSERT INTO Stock VALUES ('S', 23, 1);
INSERT INTO Stock VALUES ('M', 23, 5);
INSERT INTO Stock VALUES ('L', 23, 2);
INSERT INTO Stock VALUES ('XL', 23, 1);
INSERT INTO Stock VALUES ('XS', 24, 2);
INSERT INTO Stock VALUES ('S', 24, 2);
INSERT INTO Stock VALUES ('M', 24, 3);
INSERT INTO Stock VALUES ('L', 24, 2);
INSERT INTO Stock VALUES ('XL', 24, 1);
INSERT INTO Stock VALUES ('XS', 25, 1);
INSERT INTO Stock VALUES ('S', 25, 0);
INSERT INTO Stock VALUES ('M', 25, 0);
INSERT INTO Stock VALUES ('L', 25, 0);
INSERT INTO Stock VALUES ('XL', 25, 0);
INSERT INTO Stock VALUES ('XS', 26, 4);
INSERT INTO Stock VALUES ('S', 26, 1);
INSERT INTO Stock VALUES ('M', 26, 3);
INSERT INTO Stock VALUES ('L', 26, 2);
INSERT INTO Stock VALUES ('XL', 26, 0);
INSERT INTO Stock VALUES ('XS', 27, 5);
INSERT INTO Stock VALUES ('S', 27, 4);
INSERT INTO Stock VALUES ('M', 27, 3);
INSERT INTO Stock VALUES ('L', 27, 2);
INSERT INTO Stock VALUES ('XL', 27, 1);
INSERT INTO Stock VALUES ('XS', 28, 2);
INSERT INTO Stock VALUES ('S', 28, 1);
INSERT INTO Stock VALUES ('M', 28, 3);
INSERT INTO Stock VALUES ('L', 28, 2);
INSERT INTO Stock VALUES ('XL', 28, 1);
INSERT INTO Stock VALUES ('XS', 29, 0);
INSERT INTO Stock VALUES ('S', 29, 1);
INSERT INTO Stock VALUES ('M', 29, 3);
INSERT INTO Stock VALUES ('L', 29, 1);
INSERT INTO Stock VALUES ('XL', 29, 2);
INSERT INTO Stock VALUES ('XS', 30, 0);
INSERT INTO Stock VALUES ('S', 30, 0);
INSERT INTO Stock VALUES ('M', 30, 0);
INSERT INTO Stock VALUES ('L', 30, 0);
INSERT INTO Stock VALUES ('XL', 30, 0);
INSERT INTO Stock VALUES ('XS', 31, 3);
INSERT INTO Stock VALUES ('S', 31, 4);
INSERT INTO Stock VALUES ('M', 31, 2);
INSERT INTO Stock VALUES ('L', 31, 7);
INSERT INTO Stock VALUES ('XL', 31, 1);
INSERT INTO Stock VALUES ('XS', 32, 2);
INSERT INTO Stock VALUES ('S', 32, 0);
INSERT INTO Stock VALUES ('M', 32, 1);
INSERT INTO Stock VALUES ('L', 32, 2);
INSERT INTO Stock VALUES ('XL', 32, 0);

INSERT INTO Stock VALUES ('40', 33, 1);
INSERT INTO Stock VALUES ('41', 33, 2);
INSERT INTO Stock VALUES ('42', 33, 3);
INSERT INTO Stock VALUES ('43', 33, 2);
INSERT INTO Stock VALUES ('44', 33, 0);
INSERT INTO Stock VALUES ('45', 33, 0);
INSERT INTO Stock VALUES ('40', 34, 1);
INSERT INTO Stock VALUES ('41', 34, 1);
INSERT INTO Stock VALUES ('42', 34, 1);
INSERT INTO Stock VALUES ('43', 34, 1);
INSERT INTO Stock VALUES ('44', 34, 1);
INSERT INTO Stock VALUES ('45', 34, 1);
INSERT INTO Stock VALUES ('40', 35, 1);
INSERT INTO Stock VALUES ('41', 35, 2);
INSERT INTO Stock VALUES ('42', 35, 2);
INSERT INTO Stock VALUES ('43', 35, 1);
INSERT INTO Stock VALUES ('44', 35, 3);
INSERT INTO Stock VALUES ('45', 35, 4);
INSERT INTO Stock VALUES ('40', 36, 1);
INSERT INTO Stock VALUES ('41', 36, 0);
INSERT INTO Stock VALUES ('42', 36, 2);
INSERT INTO Stock VALUES ('43', 36, 2);
INSERT INTO Stock VALUES ('44', 36, 0);
INSERT INTO Stock VALUES ('45', 36, 1);
INSERT INTO Stock VALUES ('40', 37, 0);
INSERT INTO Stock VALUES ('41', 37, 0);
INSERT INTO Stock VALUES ('42', 37, 3);
INSERT INTO Stock VALUES ('43', 37, 2);
INSERT INTO Stock VALUES ('44', 37, 1);
INSERT INTO Stock VALUES ('45', 37, 0);
INSERT INTO Stock VALUES ('40', 38, 1);
INSERT INTO Stock VALUES ('41', 38, 0);
INSERT INTO Stock VALUES ('42', 38, 1);
INSERT INTO Stock VALUES ('43', 38, 2);
INSERT INTO Stock VALUES ('44', 38, 0);
INSERT INTO Stock VALUES ('45', 38, 0);

INSERT INTO Stock VALUES ('40', 39, 3);
INSERT INTO Stock VALUES ('41', 39, 0);
INSERT INTO Stock VALUES ('42', 39, 3);
INSERT INTO Stock VALUES ('43', 39, 2);
INSERT INTO Stock VALUES ('44', 39, 0);
INSERT INTO Stock VALUES ('45', 39, 0);
INSERT INTO Stock VALUES ('40', 40, 4);
INSERT INTO Stock VALUES ('41', 40, 0);
INSERT INTO Stock VALUES ('42', 40, 3);
INSERT INTO Stock VALUES ('43', 40, 2);
INSERT INTO Stock VALUES ('44', 40, 0);
INSERT INTO Stock VALUES ('45', 40, 0);
INSERT INTO Stock VALUES ('40', 41, 2);
INSERT INTO Stock VALUES ('41', 41, 1);
INSERT INTO Stock VALUES ('42', 41, 3);
INSERT INTO Stock VALUES ('43', 41, 2);
INSERT INTO Stock VALUES ('44', 41, 0);
INSERT INTO Stock VALUES ('45', 41, 0);
INSERT INTO Stock VALUES ('40', 42, 2);
INSERT INTO Stock VALUES ('41', 42, 1);
INSERT INTO Stock VALUES ('42', 42, 3);
INSERT INTO Stock VALUES ('43', 42, 2);
INSERT INTO Stock VALUES ('44', 42, 1);
INSERT INTO Stock VALUES ('45', 42, 1);
INSERT INTO Stock VALUES ('40', 43, 1);
INSERT INTO Stock VALUES ('41', 43, 1);
INSERT INTO Stock VALUES ('42', 43, 1);
INSERT INTO Stock VALUES ('43', 43, 1);
INSERT INTO Stock VALUES ('44', 43, 1);
INSERT INTO Stock VALUES ('45', 43, 1);
INSERT INTO Stock VALUES ('40', 44, 0);
INSERT INTO Stock VALUES ('41', 44, 0);
INSERT INTO Stock VALUES ('42', 44, 0);
INSERT INTO Stock VALUES ('43', 44, 0);
INSERT INTO Stock VALUES ('44', 44, 0);
INSERT INTO Stock VALUES ('45', 44, 0);
INSERT INTO Stock VALUES ('40', 45, 1);
INSERT INTO Stock VALUES ('41', 45, 1);
INSERT INTO Stock VALUES ('42', 45, 2);
INSERT INTO Stock VALUES ('43', 45, 1);
INSERT INTO Stock VALUES ('44', 45, 1);
INSERT INTO Stock VALUES ('45', 45, 1);
INSERT INTO Stock VALUES ('40', 46, 4);
INSERT INTO Stock VALUES ('41', 46, 1);
INSERT INTO Stock VALUES ('42', 46, 3);
INSERT INTO Stock VALUES ('43', 46, 2);
INSERT INTO Stock VALUES ('44', 46, 3);
INSERT INTO Stock VALUES ('45', 46, 2);
INSERT INTO Stock VALUES ('40', 47, 1);
INSERT INTO Stock VALUES ('41', 47, 1);
INSERT INTO Stock VALUES ('42', 47, 3);
INSERT INTO Stock VALUES ('43', 47, 2);
INSERT INTO Stock VALUES ('44', 47, 0);
INSERT INTO Stock VALUES ('45', 47, 0);
INSERT INTO Stock VALUES ('40', 48, 7);
INSERT INTO Stock VALUES ('41', 48, 2);
INSERT INTO Stock VALUES ('42', 48, 3);
INSERT INTO Stock VALUES ('43', 48, 0);
INSERT INTO Stock VALUES ('44', 48, 0);
INSERT INTO Stock VALUES ('45', 48, 2);
INSERT INTO Stock VALUES ('40', 49, 3);
INSERT INTO Stock VALUES ('41', 49, 0);
INSERT INTO Stock VALUES ('42', 49, 1);
INSERT INTO Stock VALUES ('43', 49, 2);
INSERT INTO Stock VALUES ('44', 49, 1);
INSERT INTO Stock VALUES ('45', 49, 1);
INSERT INTO Stock VALUES ('40', 50, 0);
INSERT INTO Stock VALUES ('41', 50, 2);
INSERT INTO Stock VALUES ('42', 50, 2);
INSERT INTO Stock VALUES ('43', 50, 1);
INSERT INTO Stock VALUES ('44', 50, 0);
INSERT INTO Stock VALUES ('45', 50, 1);
INSERT INTO Stock VALUES ('40', 51, 1);
INSERT INTO Stock VALUES ('41', 51, 0);
INSERT INTO Stock VALUES ('42', 51, 3);
INSERT INTO Stock VALUES ('43', 51, 2);
INSERT INTO Stock VALUES ('44', 51, 1);
INSERT INTO Stock VALUES ('45', 51, 0);
INSERT INTO Stock VALUES ('40', 52, 0);
INSERT INTO Stock VALUES ('41', 52, 1);
INSERT INTO Stock VALUES ('42', 52, 2);
INSERT INTO Stock VALUES ('43', 52, 2);
INSERT INTO Stock VALUES ('44', 52, 0);
INSERT INTO Stock VALUES ('45', 52, 3);

-- Insertion des données dans User --
INSERT INTO User VALUES('user1@example.com', 'user1', 'user1', '2023-03-28', 'mdp');
INSERT INTO User VALUES('user2@example.com', 'user2', 'user2', '2023-04-05', 'mdp');
INSERT INTO User VALUES('user3@example.com', 'user3', 'user3', '2023-04-06', 'mdp');
INSERT INTO User VALUES ('a@a.com', 'aa', 'aa', '2000-12-05', 'aa');
